site_name: ""
site_url: https://waterdipAI.github.io/waterdip/
repo_url: https://github.com/WaterdipAI/waterdip
repo_name: waterdipAI/waterdip
edit_uri: blob/main/docs/
theme:
  name: material
  logo: assets/wd_logo_white.svg
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.expand
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
nav:
  - Welcome to Waterdip: index.md
  - Introduction:
    - Introduction to Waterdip: introduction/introduction.md
    - Quick Start: introduction/quick_start.md
  - Concepts:
    - What is ML Observability: concepts/what_is_ml_observability.md
    - Metric Types:
      - Data Quality: concepts/metric_type_data_quality.md
      - Model Performance: concepts/metric_type_model_performance.md
      - Drift: concepts/metric_type_drift.md
    - Monitor & Alerts: concepts/monitor_and_alerts.md
  - Support:
    - Contact: support/contact.md

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/waterdipai/waterdip
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/waterdip
    - icon: fontawesome/brands/discord
      link: https://discord.gg/V4kjYcqhzg

copyright: "&copy; 2022 BY WATERDIP LABS"